### ISSUE TITLE
Prj Orion not working and some invulnerabilities

### ISSUE THREAD

**Issue by MarufKhan8307** [mrepol742/project-orion#101]
![Screenshot_3](https://github.com/mrepol742/project-orion/assets/79297002/536a4f82-67fd-4ece-91ec-2a251eef8b0d)
I can't run it in my host pc, and I can't understand what's wrong in render
![image](https://github.com/mrepol742/project-orion/assets/79297002/b0d5dfca-a3ab-4bb5-aaa1-1aa88493babe)
Please check and make a tutorial video on it, that will really help so much. plz plz plz

**Comment by mrepol742** [comment]
Hello @MarufKhan8307 ,

The first issue about 'clear' is not recognized as command is due to you are using window based operating system and the chatbot was created in linux operating system.
To address this issue all you need to do is to replace 'clear' with 'cls'
cls is short for clear screen for windows

It's normal for a nodejs project to have a vulnirability due to some packages uses outdated packages too..

About the render one, there is no problem on it, the cli output no account found which means you havent added your app state yet.

**Comment by MarufKhan8307** [comment]
How do I add an account ? I see no options, if u make a video on it that'd really help bro. Or just tell me what should I do next
